name: Test vcpkg ports

on:
  push:
    branches: ["vcpkg-registry"]
  pull_request:
    branches: ["vcpkg-registry"]

env:
  VCPKG_OVERLAY_PORTS: "${{ github.workspace }}/ports"
  VCPKG_TARGET_TRIPLET: "x64-linux"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Acquire vcpkg
        uses: actions/checkout@v4
        with:
          repository: "Microsoft/vcpkg"
          path: vcpkg

      - name: Bootstrap vcpkg
        run: "${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh"
        shell: bash

      - name: Test keys
        run: |
          echo "${{ hashFiles('vcpkg/scripts/buildsystems/vcpkg.cmake') }}"
          echo "${{ hashFiles('vcpkg.json') }}"
        shell: bash

      - name: Cache vcpkg dependencies
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/vcpkg_installed
          key: cache-vcpkg-${{ env.VCPKG_TARGET_TRIPLET }}-${{ hashFiles('/vcpkg/scripts/buildsystems/vcpkg.cmake') }}-${{ hashFiles('/vcpkg.json') }}
          restore-keys: |
            cache-vcpkg-${{ env.VCPKG_TARGET_TRIPLET }}-${{ hashFiles('/vcpkg/scripts/buildsystems/vcpkg.cmake') }}-
            cache-vcpkg-${{ env.VCPKG_TARGET_TRIPLET }}-

      - name: Build ports
        run: ${{ github.workspace }}/vcpkg/vcpkg install
        shell: bash
